### ISSUE TITLE
Support version as 'latest'

### ISSUE THREAD

**Issue by russellpierce** [robertzk/lockbox#126]
Sometimes you want to install a package with lockbox (to make sure that it doesn't break any of your other version requirements), but you are content to use the latest version of that package.  It might be nice in those circumstances to specify version at 'latest' and use `available.packages()` to select the version that lockbox will use on any given run.

**Comment by peterhurford** [comment]
I recall discussing this with @robertzk before and he had a preference that people be explicit about their package versions to avoid weird behavior, mainly as a good UX kind of thing.

**Comment by russellpierce** [comment]
Might that viewpoint carried forward a bit seem to suggest that all package dependency versions should be specified as well?  An unlocked package version might just be considered a script 'dependency'.  If package dependencies are allowed to float, shouldn't too script dependencies?

**Comment by peterhurford** [comment]
I'd have to let @robertzk weigh in there. Another drawback for consideration I'd point out is that any `latest` GitHub package would have to trigger a fresh download attempt on each build.

**Comment by russellpierce** [comment]
Agreed, handling for Github would be a mess.

**Comment by robertzk** [comment]
@peterhurford That was my viewpoint at the time but that was before we had automatic inference of nested dependencies. I was also concerned about making network calls on every session start-up but that seems to be a common feature of many modern dependency managers. @russellpierce I like the argument that a top-level dependency without a version specification is equivalent to a nested dependency. I'd be happy to accept a PR if you have one. The user is explicitly taking responsibility for implicit versions shifts due to the `latest` keyword, so as long as it is not a default behavior I don't see much concern.

**Comment by russellpierce** [comment]
No PR ready yet, but unless someone pops in here and says 'got it', I might take it on sometime in the next few weeks.

**Comment by russellpierce** [comment]
Inside of `lockbox.list` prior to `as.locked.package` I'm thinking something like:

```
  # Set versions for packages set to 'latest'
  latest_index <- which(lapply(lock, function(l) {l$version}) == "latest")
  if (length(latest_index) > 0) {
    available_packages <- available.packages()
    package_names <- available_packages[, "Package"]
    for (index in latest_index) {
      lock[[index]]$version <- available_packages[package_names == lock[[index]]$name, "Version"]
    }
  }
```

Thoughts?  Style preferences?

**Comment by robertzk** [comment]
@russellpierce That snippet looks good to me.
