### ISSUE TITLE
Lockbox should have the ability to get the "latest" package version

### ISSUE THREAD

**Issue by peterhurford** [robertzk/lockbox#49]

**Comment by robertzk** [comment]
You can use `ref: master`. It can't figure out the version from the DESCRIPTION file because that means every time you loaded lockbox it would have to perform N requests, where N is the number of github dependencies without version specified. This is not ideal, since new R consoles are loaded frequently.

I guess that could just mean "use any version if it exists in the lockbox cache, otherwise download the latest." Is that what you're looking for?
