### ISSUE TITLE
When lockbox is on a ref with a version and the version in the ref goes up, lockbox breaks

### ISSUE THREAD

**Issue by peterhurford** [robertzk/lockbox#86]
Maybe refs shouldn't have version numbers?

**Comment by kirillseva** [comment]
Use commit SHA or a git tag as ref instead of a branch name. Lockbox operates under the assumption that refs are immutable.

**Comment by kirillseva** [comment]
It's actually a good thing that lockbox breaks when the version on ref goes up.
Lockbox is, sadly, not a substitute for knowledge of git (and as we found out, of yaml too)

**Comment by russellpierce** [comment]
Well, maybe it is a good thing that it breaks, but surely it isn't a good thing that is breaks silently - IIRC that is the case here and with the class of similar issues around refs.

**Comment by kirillseva** [comment]
Agreed! It would be nice if it broke with a louder and more explicit error
message!

With yaml unfortunately the error appears before we get to do anything
about it, in the yaml parser. I think updating the readme to make versions
be in quotes is a good enough fix for the issue. I do prefer convention
over configuration approach to software engineering.

With this one, it's a bit tricky because not all packages are git
repositories, so we'd need some agnostic way to quickly detect version
mismatches. Other package management solutions, such as bundler, yarn,
cargo, solve it by introducing an intermediate machine-readable
representation, like gemfile.lock, that allows for reproducible builds. In
our case, such "locked" lockfile (I'm open for a better name) would contain
information about the order in which packages should be loaded, their
versions, would include the derived dependencies, and we could then easily
add features such as checksumming (that would help us raise a clever error
message in this case). Should probably open another issue for this proposal
