### ISSUE TITLE
If you transition from a locally developed package to the one on github, you can have a stale cache

### ISSUE THREAD

**Issue by peterhurford** [robertzk/lockbox#97]
Unless you increment the version right before switching to GitHub, the lockbox will still have your oldest local version (which could be quite old if you use autoinstall). This will need to be removed manually.

Maybe lockbox directories can have metadata and if the installation remote changes, that version is wiped and reinstalled in your lockbox?

**Comment by robertzk** [comment]
Theoretically, the same version should have the same package contents regardless of remote. If one is developing a package locally and the contents of the package expect to change while the version remains constant (and we want to preserve the current behavior of installing the package instead of using `devtools::load_all`) then there could be weird conflicts if, e.g., one project's lockfile asserts a local remote and another project's lockfile asserts a github remote with the same version.

I can't remember at the moment, but what was wrong with the idea of using `load_all` on packages with a local remote?

**Comment by peterhurford** [comment]
Right now, we only use `load_all` for local remotes if `autoinstall` is TRUE.

**Comment by russellpierce** [comment]
@peterhurford Should we state the resolution here?  Determined as a won't fix because versions shouldn't be different between local development and github for a particular version?

**Comment by peterhurford** [comment]
Resolution is that I decided that `autoinstall = TRUE` should be sufficient and otherwise you should increment the package version when you make changes.
